
INSERT INTO "user" (USERNAME, PASSWORD,FIRSTNAME,LASTNAME,EMAIL,PHONE,ENABLED) VALUES ('tirth_123', '$2y$12$XvzApUHGBETBJsGlnZSUweFN6nbUasSjikol7xweHXD1xidQSCEZy',
'tirth','chaudhary','tirth12@gmail.com','+91 9847388338','true');

INSERT INTO USERROLE (USERID,ROLE) VALUES ('1','admin');