CREATE TABLE USER( 
USERID BIGINT AUTO_INCREMENT PRIMARY KEY, 
USERNAME VARCHAR(128) NOT NULL UNIQUE, 
PASSWORD VARCHAR(256) NOT NULL, 
FIRSTNAME VARCHAR(50) NOT NULL, 
LASTNAME VARCHAR(50) NOT NULL, 
EMAIL VARCHAR(50) NOT NULL UNIQUE, 
PHONE CHAR(14) NOT NULL UNIQUE
);
  
  CREATE TABLE USER_ROLE( 
  ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY, 
  USERNAME VARCHAR(128) NOT NULL, 
  ROLE VARCHAR(10) NOT NULL
  )